### ISSUE TITLE
Accessing Docker version of Matchminer with Docker Volumes

### ISSUE THREAD

**Issue by RobertScalfani** [dfci/matchminer#5]
Hello,
Using the Docker script works great, but we would like to set up volumes with the docker images that the script runs for matchminer. Using the script text at https://storage.googleapis.com/matchminer_demo/matchminer.sh, we can edit the script file to customize the docker build and run the script locally. We're looking to add a line `-v ~/Documents:/DOCKER_VOLUME_DIRECTORY` to the script to add volumes for a few of the images that are run (`matchminer/mmelastic` and `mongo`). However, we're not sure what the directory structure is so that we can choose the correct location for DOCKER_VOLUME_DIRECTORY. Could you advise as to what this directory location should be so that we can set up volumes?
Thank you.

**Comment by ethansiegl** [comment]
Hi Robert. I'm not sure I follow what you're asking exactly. Could you describe what you're trying to do at a slightly higher level? Are you trying to stand up an instance of MatchMiner?

As far as volumes are concerned, if you want to mount a directory into a running container, you should be able to do that by modifying the `docker-compose.yml` file under the `volumes` key. 

If you could clarify what you mean by "directory structure," I'll be able to help more.

**Comment by RobertScalfani** [comment]
Hi Ethan, thank you for your quick response!
It sounds like modifying the `docker-compose.yml` is the way to go - however I can't seem to find the file. Apologies if I'm just missing it but where would I find it?

**Comment by ethansiegl** [comment]
Hi Robert, sorry about that. There's isn't a `docker-compose.yml` file available currently, but you should be able to alter the script's `docker run [CMD] -v [DIR]:[DIR]` commands to add whatever directories you need to access. Does that help?

**Comment by RobertScalfani** [comment]
Yes it does thank you!
The last clarification I can use is what directory `[DIR]` within the container should be used? In other words, what is the second directory `[DIR]` after the colon in the `docker run [CMD] -v [DIR]:[DIR]` command you gave for the different images in the script?

**Comment by ethansiegl** [comment]
Sure, sorry for the delayed reply. The bind volume mount uses the typical docker syntax. In more detail:
`docker run [CMD] -v [LOCAL_DIR]:[MOUNT_DIR]`

So if you wanted to make a directory available within the container, you could use this command:
`docker run [CMD] -v /user/robert/some/dir:/usr/local/container/dir` 

The [docker docs](https://docs.docker.com/storage/bind-mounts/) have pretty good documentation on this too if you want to take a closer look
